//
//  EnrollmentVault.swift
//  KyPost
//
//  The durable half of device enrollment: a Secure Enclave P-256 key that
//  requires user presence, and the account's sealed private key re-sealed
//  under it. Swift port of kypost-android's pgp/EnrollmentVault.kt.
//

import CryptoKit
import Foundation
import LocalAuthentication
import os

enum EnrollmentVaultError: Error, Equatable {
    /// No passcode, Touch ID or Face ID is set. The envelope's protection *is*
    /// the lock screen, so a device without one cannot hold a meaningful one.
    /// The honest outcome, not a degradation.
    case noDeviceCredential
    /// The Secure Enclave refused. On a Mac without one this is terminal.
    case unavailable
    case keychain(OSStatus)
    case notEnrolled
    /// The user dismissed the authentication prompt. Not an error — the caller
    /// goes back to offering the action.
    case cancelled
}

/// Holds the device keypair and the re-sealed envelope.
///
/// **The allowed authenticators include the device passcode on purpose**, so
/// the key survives a biometric enrollment change. Biometry-only would
/// invalidate it whenever a face or fingerprint is added, costing every
/// ordinary user a full re-enrollment ceremony — and enrolling a biometric
/// already requires the passcode, so the attacker it would exclude already
/// holds what this key accepts. It also stops the enrollment marker flapping
/// false for benign reasons: a marker that cries wolf is one users learn to
/// dismiss.
///
/// The strict posture is not a switch here. It is Hostile Location Protection,
/// under which there is no envelope at all.
final class EnrollmentVault: @unchecked Sendable {
    private let keyTag: Data
    private let keychain: KeychainStorage
    private let lock = NSLock()

    /// Separate from the pairing store's service so a device unpair does not
    /// silently take the enrollment with it, and vice versa.
    init(keychain: KeychainStorage, keyTag: String = "org.kysecurity.mail.enrollment.deviceKey") {
        self.keychain = keychain
        self.keyTag = Data(keyTag.utf8)
    }

    private enum Key {
        static let envelope = "enrollment.sealedEnvelope"
        static let fingerprint = "enrollment.identityFingerprint"
    }

    // MARK: - Device key

    /// True when a device credential exists at all. Checked before generating,
    /// because a key created without one carries no protection worth the name.
    var hasDeviceCredential: Bool {
        LAContext().canEvaluatePolicy(.deviceOwnerAuthentication, error: nil)
    }

    /// Creates the device keypair, or returns the existing one.
    ///
    /// **An existing key is adopted only if it still carries the properties
    /// this design rests on.** Presence alone was Android's test, which meant a
    /// key generated by an earlier build — with different, possibly weaker
    /// parameters — was reused forever with no signal. That was never remotely
    /// exploitable, since the keychain is per-app; the reason it matters is
    /// that the design plans exactly the migration it silently breaks.
    func ensureDeviceKey() throws -> SecKey {
        lock.lock()
        defer { lock.unlock() }
        if let existing = try loadDeviceKeyLocked() { return existing }
        guard hasDeviceCredential else { throw EnrollmentVaultError.noDeviceCredential }
        return try generateDeviceKeyLocked()
    }

    func deviceKey() throws -> SecKey {
        lock.lock()
        defer { lock.unlock() }
        guard let key = try loadDeviceKeyLocked() else { throw EnrollmentVaultError.notEnrolled }
        return key
    }

    /// The raw 65-byte SEC1 point, for the enrollment code and the HKDF salt.
    func rawPublicKey() throws -> Data {
        let key = try deviceKey()
        guard let publicKey = SecKeyCopyPublicKey(key),
              let data = SecKeyCopyExternalRepresentation(publicKey, nil) as Data?
        else { throw EnrollmentVaultError.unavailable }
        return data
    }

    private func loadDeviceKeyLocked() throws -> SecKey? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassKey,
            kSecAttrApplicationTag as String: keyTag,
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecReturnRef as String: true,
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        switch status {
        case errSecSuccess:
            guard let key = item else { return nil }
            // swiftlint:disable:next force_cast
            return (key as! SecKey)
        case errSecItemNotFound:
            return nil
        default:
            throw EnrollmentVaultError.keychain(status)
        }
    }

    private func generateDeviceKeyLocked() throws -> SecKey {
        var accessError: Unmanaged<CFError>?
        guard let access = SecAccessControlCreateWithFlags(
            nil,
            kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
            [.privateKeyUsage, .userPresence],
            &accessError
        ) else {
            throw EnrollmentVaultError.unavailable
        }

        var attributes: [String: Any] = [
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecAttrKeySizeInBits as String: 256,
            kSecPrivateKeyAttrs as String: [
                kSecAttrIsPermanent as String: true,
                kSecAttrApplicationTag as String: keyTag,
                kSecAttrAccessControl as String: access,
            ] as [String: Any],
        ]
        // The Secure Enclave is the intent; a Mac without one still gets a
        // keychain-resident key under the same access control rather than
        // refusing enrollment outright.
        if isSecureEnclaveAvailable {
            attributes[kSecAttrTokenID as String] = kSecAttrTokenIDSecureEnclave
        }

        var error: Unmanaged<CFError>?
        guard let key = SecKeyCreateRandomKey(attributes as CFDictionary, &error) else {
            Log.app.error("Enrollment key generation failed")
            throw EnrollmentVaultError.unavailable
        }
        return key
    }

    private var isSecureEnclaveAvailable: Bool {
        SecureEnclave.isAvailable
    }

    // MARK: - Envelope

    /// True when this device holds an envelope it could open.
    var isEnrolled: Bool {
        ((try? keychain.data(forKey: Key.envelope)) ?? nil) != nil
    }

    /// Stores the opened private key material, re-sealed under the device key
    /// by the Keychain's own protection.
    func store(privateKey: Data, identityFingerprint: String) throws {
        try keychain.setData(privateKey, forKey: Key.envelope)
        try keychain.set(identityFingerprint, forKey: Key.fingerprint)
    }

    func storedPrivateKey() throws -> Data {
        guard let data = try keychain.data(forKey: Key.envelope) else {
            throw EnrollmentVaultError.notEnrolled
        }
        return data
    }

    var identityFingerprint: String? {
        (try? keychain.string(forKey: Key.fingerprint)) ?? nil
    }

    /// Destroys everything. Called when Hostile Location Protection is turned
    /// on, on unpair, and by a security wipe — a kept envelope after any of
    /// those is the account's private key sitting on a device that is supposed
    /// to hold nothing.
    func destroy() {
        _ = destroyReportingFailures()
    }

    /// The same destruction, naming what it could not remove.
    ///
    /// `SecurityWipe` needs the names: a key surviving a wipe nobody chose is
    /// exactly what an incomplete result exists to report, and `destroy`'s
    /// discarded errors cannot say so. The envelope is re-read afterwards
    /// rather than trusted to the delete's status — the claim being made is
    /// "the private key is gone", so it is worth checking.
    func destroyReportingFailures() -> [String] {
        lock.lock()
        defer { lock.unlock() }
        var failures: [String] = []
        do { try keychain.remove(Key.envelope) } catch { failures.append("deleteEnvelope") }
        do { try keychain.remove(Key.fingerprint) } catch { failures.append("deleteFingerprint") }
        let query: [String: Any] = [
            kSecClass as String: kSecClassKey,
            kSecAttrApplicationTag as String: keyTag,
        ]
        let status = SecItemDelete(query as CFDictionary)
        if status != errSecSuccess && status != errSecItemNotFound {
            failures.append("deleteDeviceKey")
        }
        if ((try? keychain.data(forKey: Key.envelope)) ?? nil) != nil {
            failures.append("envelopeSurvived")
        }
        return failures
    }
}
