//
//  TestPgpFixtures.swift
//  KyPost Tests
//
//  A disposable, passphrase-free ed25519/cv25519 key and messages encrypted,
//  signed and deliberately mis-made for it — all produced by **gpg**, ported
//  verbatim from kypost-android's pgp/TestPgpPrivateKey.kt.
//
//  gpg on purpose. A fixture generated by the implementation under test only
//  proves that implementation agrees with itself; the whole risk in a mail
//  client's crypto is what *other people's* OpenPGP software emits. These
//  bytes came from neither GopenPGP nor Bouncy Castle, and the same bytes now
//  hold both clients to the same answers.
//
//  Never a real key.
//

enum TestPgpFixtures {
    /// gpg's own reported fingerprint for this key.
    static let fingerprint = "B30ACD64E04B8E1B0379A3201D6BDF093FAD1D11"

    static let expectedPlaintext = "Hello from a real OpenPGP message.\n"
    static let unprotectedPlaintext = "Unprotected legacy message.\n"
    static let detachedSignatureBody = "Hello from a detached signature.\n"

    static let armoredPrivate = """
    -----BEGIN PGP PRIVATE KEY BLOCK-----

    lFgEanXKfhYJKwYBBAHaRw8BAQdA2rBAx6x5YF+ObBFQBXF+/2csH6f0qPdhr1ag
    i2N5i44AAQCcI5HtSSpyFdm1apjsdPP/oSSL46Btyofhqqe7izRdLhHitCpQZ3BE
    ZWNyeXB0b3JUZXN0IDxkZWNyeXB0QGV4YW1wbGUuaW52YWxpZD6IkAQTFgoAOBYh
    BLMKzWTgS44bA3mjIB1r3wk/rR0RBQJqdcp+AhsDBQsJCAcCBhUKCQgLAgQWAgMB
    Ah4BAheAAAoJEB1r3wk/rR0RGwIA/3DvjicIsZAjVJYjTdPCsYrYbycQ6JUmtKEF
    zHjImBW4AQDinfWUlzlme+nnz+Ba//Axhd1mG5jbCzvbuBqdaFO0D5xdBGp1yoMS
    CisGAQQBl1UBBQEBB0B1Hj+iZWHELCD46VW53zsWvt/gaj5zmPw8Q3zTJRNydAMB
    CAcAAP9MfEiba0BwC3gPCGNnBSpVT6ItjQ2pBmc/6tkGpZmyOAyriHgEGBYKACAW
    IQSzCs1k4EuOGwN5oyAda98JP60dEQUCanXKgwIbDAAKCRAda98JP60dEYRUAP9v
    3DLng8XERhSTtj1xklvWLmm+PNj9sIfTevTwFlR1EwEAqFTrsMbz8SfXD5x0TvHL
    KrCer7RkZAcLVY8rcoru9Ao=
    =56KP
    -----END PGP PRIVATE KEY BLOCK-----
    """

    static let armoredPublic = """
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mDMEanXKfhYJKwYBBAHaRw8BAQdA2rBAx6x5YF+ObBFQBXF+/2csH6f0qPdhr1ag
    i2N5i460KlBncERlY3J5cHRvclRlc3QgPGRlY3J5cHRAZXhhbXBsZS5pbnZhbGlk
    PoiQBBMWCgA4FiEEswrNZOBLjhsDeaMgHWvfCT+tHREFAmp1yn4CGwMFCwkIBwIG
    FQoJCAsCBBYCAwECHgECF4AACgkQHWvfCT+tHREbAgD/cO+OJwixkCNUliNN08Kx
    ithvJxDolSa0oQXMeMiYFbgBAOKd9ZSXOWZ76efP4Fr/8DGF3WYbmNsLO9u4Gp1o
    U7QPuDgEanXKgxIKKwYBBAGXVQEFAQEHQHUeP6JlYcQsIPjpVbnfOxa+3+BqPnOY
    /DxDfNMlE3J0AwEIB4h4BBgWCgAgFiEEswrNZOBLjhsDeaMgHWvfCT+tHREFAmp1
    yoMCGwwACgkQHWvfCT+tHRGEVAD/b9wy54PFxEYUk7Y9cZJb1i5pvjzY/bCH03r0
    8BZUdRMBAKhU67DG8/En1w+cdE7xyyqwnq+0ZGQHC1WPK3KK7vQK
    =Cbik
    -----END PGP PUBLIC KEY BLOCK-----
    """

    /// Decrypts to `expectedPlaintext`, signed by this same key.
    static let armoredMessage = """
    -----BEGIN PGP MESSAGE-----

    hF4DIE6jVovIid0SAQdAGRbD7Tnkx/XA3SYjkTeY5cHfPkY7TzOUolNd9Yw38Uow
    miO6k16SpQCyugWrXGUE9kpTuVLw6+i8hHTfwCl9asERt0cNvp3MLklxjmiTGgwO
    0sAaAYGxUQZ4CukpripClMv7C5F4u8MSa+PfHFYViEL/sie2alUtWEYijrcmpr8r
    DHjuFCddDnUBT70SA4DDt+VxwQdS7R5FgY9vUf/WgdcjnP6DZpua6LjegMyjgJg3
    1fd58ly3ZLkPGe3LzNzvJ9YouCZsvKaPYMeb3sw+VQL9ZQaNzD23zkSrvkwc2gQ1
    NCo8FMo5AKlEZKUkoL9euSY/d09tCpZlJk/hjEkizqw67Bjk/jzirNTWaZsGsf9y
    U5qTeneHshndLGw3O6ncuPQBWHANvJU07E/TmgQ=
    =/cZ5
    -----END PGP MESSAGE-----
    """

    static let armoredMimeMessage = """
    -----BEGIN PGP MESSAGE-----

    hF4DIE6jVovIid0SAQdA5ua6l9wfANzlnQecHQ0D9rUipmHc8/vNT8fm3h/wu38w
    t3e5oQ02X6P7SpU6Ei+7T2Yta6eoaTNmtgTXox+fWktVOlg7U/t9+pRzrKMADfp/
    0sBOAbtAD6y7d+lepNAuDdaYgzEghz7s/y9ydJwpZm1tyxFpCkWt1aCZnIhGFuHT
    8jTC0vmnXylqaJMRO+mf0rqsJ7BY+llCKSQrMaonZhoBdKWvBM3Gnr3KOmhAEy8/
    e5vuXYxkTztLhs2J51D6uRyu60HxbQmKsz2J7UdqhLdaEdxupY94zH8sFZf5fEkg
    xLKizkrlGkrpCu55/O1alebV2VV8EaM7qLh8J9bkdNcgADO7y9UAU2P8VJfBKg8o
    e+4BbrTWLuH03boQtlUkuuvUvPVTBxt9lMtN8oDnsKMp87N6JCYCW82yqkwHxizO
    0ziPcaakdFDBOWrlUS5BjUwTvagnbIoT1izHOmDQVmop
    =kdmH
    -----END PGP MESSAGE-----
    """

    /// A legacy Symmetrically Encrypted Data (tag 9) packet, made with
    /// `gpg --rfc2440 --disable-mdc`. It carries no integrity protection, so
    /// decrypting it must fail closed — an unprotected message is malleable,
    /// and rendering one as ordinary mail is how a tampered ciphertext gets
    /// believed.
    static let armoredUnprotectedMessage = """
    -----BEGIN PGP MESSAGE-----

    hF4DIE6jVovIid0SAQdAWHqPbgM+XRAGZC+xKnEonHOJT093AlXrz6OuuPetnR4w
    nUccPxkOY2eWnMNe3r2wXcnqDpoum903e10u/uGyepidKhjAE+igYxAAvbshmjoL
    yUDXCoX+hCK3Ph7RbvZAGV5LW5c0wivJeaKewBT1ZhPoE6YXzJfsLt2YkXUTsYai
    zg6eRYlo3dLJ0eIyMpN2WPQG
    =3Eds
    -----END PGP MESSAGE-----
    """

    static let armoredDetachedSignature = """
    -----BEGIN PGP SIGNATURE-----

    iHUEABYKAB0WIQSzCs1k4EuOGwN5oyAda98JP60dEQUCanYIIgAKCRAda98JP60d
    EbWNAP9fwxWqBGi3C7s/omp5dfSZas7SdeapITPDfYGbIpYbgwEAsgZeCY4pI2zs
    vtCCtajHfEiFMQp00CyzHSuLbWNaBAg=
    =KR0w
    -----END PGP SIGNATURE-----
    """


    /// A second, unrelated gpg key. Offering this as the signer must not
    /// launder a signature made by the first one into validity.
    static let unrelatedPublicKey = """
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mDMEantA0hYJKwYBBAHaRw8BAQdAkYTGprf6M3BnWSBhudzXPtE0uEfRdKFL/DrG
    8Uj4Bum0LFNlY29uZFJlY2lwaWVudFRlc3QgPHNlY29uZEBleGFtcGxlLmludmFs
    aWQ+iJAEExYKADgWIQTkVen3btUyBP9TPL1qixELvdckggUCantA0gIbAwULCQgH
    AgYVCgkICwIEFgIDAQIeAQIXgAAKCRBqixELvdckgiXdAP9fqAqnHvUQ4UGX94q1
    nEHM4T8UEQjrlLueL8COMbrJNwEAq+olwbjNBFan2dVTdu4mbIFW92dBuHTVZiau
    r1sFGQO4OARqe0DSEgorBgEEAZdVAQUBAQdAktFPYvB1lD8Y0iq7P8yc1OHRej3o
    xVNQ8CF2E3Fd/HkDAQgHiHgEGBYKACAWIQTkVen3btUyBP9TPL1qixELvdckggUC
    antA0gIbDAAKCRBqixELvdckglHSAQCt/vydza9tds8pnMSM2WoCJbcDRxtxtbTy
    OLkwshHnzAEAvtPtX9vBbz3DUWABq8kOHK2BlzJluGl9ycgEJMC8Xwk=
    =2K/C
    -----END PGP PUBLIC KEY BLOCK-----
    """


    /// The private half of `unrelatedPublicKey`, so a test can hold a key that
    /// did *not* sign the message it is opening — the only arrangement in
    /// which "was this signature verified by a key we were offered?" is
    /// actually being asked.
    static let unrelatedPrivate = """
    -----BEGIN PGP PRIVATE KEY BLOCK-----
        
    lFgEantA0hYJKwYBBAHaRw8BAQdAkYTGprf6M3BnWSBhudzXPtE0uEfRdKFL/DrG
    8Uj4BukAAP4n3F3oLkRieY9rq0ksZ5AlVSBVt+A4zfd9a0fc7apmYxCRtCxTZWNv
    bmRSZWNpcGllbnRUZXN0IDxzZWNvbmRAZXhhbXBsZS5pbnZhbGlkPoiQBBMWCgA4
    FiEE5FXp927VMgT/Uzy9aosRC73XJIIFAmp7QNICGwMFCwkIBwIGFQoJCAsCBBYC
    AwECHgECF4AACgkQaosRC73XJIIl3QD/X6gKpx71EOFBl/eKtZxBzOE/FBEI65S7
    ni/AjjG6yTcBAKvqJcG4zQRWp9nVU3buJmyBVvdnQbh01WYmrq9bBRkDnF0EantA
    0hIKKwYBBAGXVQEFAQEHQJLRT2LwdZQ/GNIquz/MnNTh0Xo96MVTUPAhdhNxXfx5
    AwEIBwAA/0bSqp9/+ij+NzbykVNngdxHdY0YbK9wUcLCJCA8iO1gERyIeAQYFgoA
    IBYhBORV6fdu1TIE/1M8vWqLEQu91ySCBQJqe0DSAhsMAAoJEGqLEQu91ySCUdIB
    AK3+/J3Nr212zymcxIzZagIltwNHG3G1tPI4uTCyEefMAQC+0+1f28FvPcNRYAGr
    yQ4crYGXMmW4aX3JyAQkwLxfCQ==
    =ysk8
    -----END PGP PRIVATE KEY BLOCK-----
    """
}
